# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 13:33
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('ssh_public_key', models.FileField(blank=True, null=True, upload_to=account.models.upload_to)),
                ('pgp_public_key', models.FileField(blank=True, null=True, upload_to=account.models.upload_to)),
                ('company', models.CharField(max_length=200)),
                ('oauth_token', models.CharField(max_length=1024)),
                ('oauth_secret', models.CharField(max_length=1024)),
                ('jira_url', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
