# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jira_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
