##############################################################################
# Copyright (c) 2018 Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
$schema: 'http://json-schema.org/schema#'
$id: 'https://github.com/opnfv/pharos/blob/master/config/pdf/pod1.yaml'

definitions:
  net_config:
    v0.1:
      # NOTE: I hope this is going away soon, so I won't model it yet
      type: 'object'
  daisy:
    v0.1:
      type: 'object'
      # NOTE: To be properly modeled by Daisy maintainers
  fuel:
    v0.1:
      type: 'object'
      properties:
        jumphost:
          type: 'object'
          properties:
            bridges:
              type: 'object'
              properties:
                admin:
                  type: ['string', 'null']
                mgmt:
                  type: ['string', 'null']
                private:
                  type: ['string', 'null']
                public:
                  type: ['string', 'null']
              required: ['admin', 'mgmt', 'private', 'public']
              additionalProperties: false
          required: ['bridges']
          additionalProperties: false
        network:
          type: 'object'
          properties:
            node:
              type: 'array'
              items:
                type: 'object'
                properties:
                  interfaces:
                    type: 'array'
                    items:
                      type: ['string', 'null']
                  busaddr:
                    type: 'array'
                    items:
                      type: ['string', 'null']
                required: ['interfaces', 'busaddr']
                additionalProperties: false
          required: ['node']
          additionalProperties: false
      required: ['jumphost', 'network']
      additionalProperties: false

# Do not allow any properties not defined here. This lets us catch typos.
additionalProperties: false

properties:
  idf:
    oneOf:
      # Each new IDF version should get a new list entry
      # NOTE: subsections can have their own version, all v0.1 for IDF v0.1
      - type: 'object'
        required: ['version', 'net_config']
        additionalProperties: false
        properties:
          version:
            type: 'number'
            enum: [0.1]
          net_config:
            $ref: '#/definitions/net_config/v0.1'
          fuel:
            $ref: '#/definitions/fuel/v0.1'
          daisy:
            $ref: '#/definitions/daisy/v0.1'
