# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenkinsSlave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='offline', max_length=30)),
                ('url', models.CharField(max_length=1024)),
                ('ci_slave', models.BooleanField(default=False)),
                ('dev_pod', models.BooleanField(default=False)),
                ('building', models.BooleanField(default=False)),
                ('last_job_name', models.CharField(default='', max_length=1024)),
                ('last_job_url', models.CharField(default='', max_length=1024)),
                ('last_job_scenario', models.CharField(default='', max_length=50)),
                ('last_job_branch', models.CharField(default='', max_length=50)),
                ('last_job_installer', models.CharField(default='', max_length=50)),
                ('last_job_result', models.CharField(default='', max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'jenkins_slave',
            },
        ),
        migrations.CreateModel(
            name='JenkinsStatistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offline', models.BooleanField(default=False)),
                ('idle', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jenkins.JenkinsSlave')),
            ],
            options={
                'db_table': 'jenkins_statistic',
            },
        ),
    ]
