# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160816_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pgpkey',
            new_name='pgp_pupblic_key',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='sshkey',
            new_name='ssh_public_key',
        ),
    ]
