# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160819_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pgp_pupblic_key',
            new_name='pgp_public_key',
        ),
    ]
