# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160812_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_complete',
        ),
    ]
