# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_registration_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresource',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='userresource',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserResource',
        ),
    ]
