# Refer from: https://github.com/opnfv/apex/blob/master/config/network/network_settings.yaml
#
# This Network description file defines Network Environment for a
# Baremetal Deployment of OPNFV. It contains default values
# for 4 following networks at least:
# - admin
# - tenant/private
# - external/public
# - storage
#
# Detailed description for these networks
#
# "admin": is the short name for Control Plane Network.
#     During OPNFV deployment it is used for node provisioning which will require
#     **PXE booting** as well as running a DHCP server on this network.  Be sure to
#     disable any other DHCP/TFTP server on this network.
#     This network should be **IPv4** even it is an IPv6 deployment,
#     IPv6 does not have PXE boot support.
#     Native vlan or no vlan configured for this network.
#
# "tenant" or "private": is the network used for tenant traffic.
#
# "external" or "public": is the network used for internet or external connectivity.
#     External OpenStack networks will be configured to egress this network.
#     There can be multiple external networks, but only one assigned as
#     "public" which OpenStack public API's will register.
#
# "storage": is the network for storage I/O.
#
# "api": is an optional network for splitting out OpenStack service API communication.
#     This should be used for IPv6 deployments.
#
# installer_vm: is deployed by OPNFV installer, such as apex undercloud, fuel master
#
network-config-metadata:
  title: Node_name network config
  version: 0.1
  created: Feb 7 2017
  comment: For Infra WG review

# DNS Settings
dns_nameservers:
  - 8.8.8.8
  - 8.8.4.4

# NTP servers
ntp:
  - 0.se.pool.ntp.org
  - 1.se.pool.ntp.org

# Syslog server: Optional
syslog:
  server: 10.128.1.24
  transport: 'tcp'

# Common network settings
networks:                            # Network configurations
  admin:                             # Admin configuration (pxe and jumpstart),
    enabled: true
    installer_vm:                    # Network settings for the Installer VM on admin network
      nic_type: interface            # Indicates if this VM will be bridged to an interface, or to a bond
      members:
        - em1                        # Member Interface to bridge to for installer VM (use multiple values for bond)
      vlan: native                   # VLAN tag to use for this network on Installer VM, native means none
      ip: 10.20.0.2                  # IP to assign to Installer VM on this network
    gateway: 10.20.0.1               # Gateway (only needed when public_network is disabled)
    cidr: 10.20.0.0/24               # Subnet in CIDR format 192.168.1.0/24
    dhcp_range:                      # DHCP range for the admin network, if empty it will be automatically provisioned
      - 10.20.0.3                    # start from
      - 10.20.0.100                  # end at
    nic_mapping:                     # Mapping of network configuration for Overcloud Nodes
      compute:                       # Mapping for compute profile (nodes that will be used as Compute nodes)
        phys_type: interface         # Physical interface type (interface or bond)
        members:                     # Physical NIC members of this mapping (Single value allowed for interface phys_type)
          - nic1
      controller:                    # Mapping for controller profile (nodes that will be used as Controller nodes)
        phys_type: interface
        members:
          - nic1
                                     #
  tenant:                            # Tenant network configuration
    enabled: true
    cidr: 192.168.1.0.0/24           # Subnet in CIDR format 192.168.1.0/24
    mtu: 4000                        # Tenant network MTU
    segmentation_type: vxlan         # Tenant network segmentation type:
                                     # vlan, vxlan, gre
    nic_mapping:                     # Mapping of network configuration for Overcloud Nodes
      compute:                       # Mapping for compute profile (nodes that will be used as Compute nodes)
        phys_type: interface         # Physical interface type (interface or bond)
        vlan: 201                    # VLAN tag to use with this NIC
        members:                     # Physical NIC members of this mapping (Single value allowed for interface phys_type)
          - nic2                     # Note, for Apex you may also use the logical nic name (found by nic order), such as "nic1"
      controller:                    # Mapping for controller profile (nodes that will be used as Controller nodes)
        phys_type: interface
        vlan: 201
        members:
          - nic2                     # Note, for Apex you may also use the logical nic name (found by nic order), such as "nic1"
                                     #
  external:                          # Can contain 1 or more external networks
    - public:                        # "public" network will be the network the installer VM attaches to
      enabled: true
      mtu: 1500                      # Public network MTU
      installer_vm:                  # Network settings for the Installer VM on admin network (note only valid on 'public' external network)
        nic_type: interface          # Indicates if this VM will be bridged to an interface, or to a bond
        vlan: native
        members:
          - em1                      # Member Interface to bridge to for installer VM (use multiple values for bond)
        ip: 172.10.1.1               # IP to assign to Installer VM on this network
      cidr: 172.10.1.0/24
      gateway: 172.10.1.0
      floating_ip_range:             # Range to allocate to floating IPs for the public network with Neutron
        - 172.10.1.100               # start from
        - 172.10.1.200               # end at
      nic_mapping:                   # Mapping of network configuration for Overcloud Nodes
        compute:                     # Mapping for compute profile (nodes that will be used as Compute nodes)
          phys_type: interface       # Physical interface type (interface or bond)
          vlan: 202                  # VLAN tag to use with this NIC
          members:                   # Physical NIC members of this mapping (Single value allowed for interface phys_type)
            - nic3
        controller:                  # Mapping for controller profile (nodes that will be used as Controller nodes)
          phys_type: interface
          vlan: 202
          members:
            - nic3
  storage:                           # Storage network configuration
    enabled: true
    cidr: 192.168.3.0/24             # Subnet in CIDR format
    mtu: 1500                        # Storage network MTU
    nic_mapping:                     # Mapping of network configuration for Overcloud Nodes
      compute:                       # Mapping for compute profile (nodes that will be used as Compute nodes)
        phys_type: interface         # Physical interface type (interface or bond)
        vlan: 203                    # VLAN tag to use with this NIC
        members:                     # Physical NIC members of this mapping (Single value allowed for interface phys_type)
          - nic4                     # Note, for Apex you may also use the logical nic name (found by nic order), such as "nic1"
      controller:                    # Mapping for controller profile (nodes that will be used as Controller nodes)
        phys_type: interface
        vlan: 203
        members:
          - nic4

