##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# hu.zhijiang@zte.com.cn
# sun.jing22@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
adapter: ipmi
hosts:
  - name: 'controller01'
    roles:
      - 'CONTROLLER_LB'
    ipmi_ip: 192.168.176.166
    ipmi_user: zteroot
    ipmi_pass: superuser
    mac_addresses:
      - 74:4a:a4:03:bf:96
      - 74:4a:a4:05:ee:86
  - name: 'computer01'
    roles:
      - 'COMPUTER'
    ipmi_ip: 192.168.176.167
    ipmi_user: zteroot
    ipmi_pass: superuser
    mac_addresses:
      - 74:4a:a4:03:bf:c6
      - 74:4a:a4:05:ee:9a
  - name: 'computer02'
    roles:
      - 'COMPUTER'
    ipmi_ip: 192.168.176.168
    ipmi_user: zteroot
    ipmi_pass: superuser
    mac_addresses:
      - 74:4a:a4:03:bf:fe
      - 74:4a:a4:05:ee:7e
disks:
  daisy: 50
daisy_passwd: 'r00tme'
daisy_ip: '10.20.7.2'
daisy_gateway: '10.20.7.1'
ceph_disk_name: '/dev/sdb'

