##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
# hu.zhijiang@zte.com.cn
# sun.jing22@zte.com.cn
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

##############################################################################
# Description
# MANAGEMENT: used for PXE, vlan used
# STORAGE: used for storage access
# EXTERNAL: used for communication with vm,
#     use same interface with TENANT in dpdk scenario
# PUBLICAPI: used for horizon access, openstack API access
# TENANT: used for tenant access, vlan and VxLan supported, default VxLan
##############################################################################
---
network-config-metadata:
  title: 'Deployment Adapter for baremetal POD'
  version: '0.1'
  created: 'Sep 13 2017'
  comment: 'For Daisy initial'
networks:
  - cidr: '10.20.7.0/24'
    gateway: '10.20.7.1'
    ip_ranges:
      - 'start': '10.20.7.3'
        'end': '10.20.7.254'
    vlan_id: null
    name: 'MANAGEMENT'
  - cidr: '10.20.7.0/24'
    gateway: '10.20.7.1'
    ip_ranges:
      - 'start': '10.20.7.3'
        'end': '10.20.7.254'
    vlan_id: null
    name: 'STORAGE'
  - cidr: '172.71.0.0/24'
    gateway: '172.71.0.1'
    ip_ranges:
      - 'start': '172.71.0.3'
        'end': '172.71.0.254'
    vlan_id: null
    'name': 'EXTERNAL'
    network_name: 'admin_external'
    mapping: 'physnet1'
  - cidr: '10.20.7.0/24'
    gateway: '10.20.7.1'
    ip_ranges:
      - 'start': '10.20.7.3'
        'end': '10.20.7.254'
    vlan_id: null
    name: 'PUBLICAPI'
  - cidr: '172.70.0.0/24'
    ip_ranges:
      - 'start': '172.70.0.3'
        'end': '172.70.0.254'
    vlan_id: null
    name: 'TENANT'
  - cidr: '10.20.7.0/24'
    gateway: '10.20.7.1'
    ip_ranges:
      - 'start': '10.20.7.3'
        'end': '10.20.7.254'
    vlan_id: null
    name: 'HEARTBEAT'
interfaces:
  - name: 'EXTERNAL'
    interface: 'ens44f0'
  - name: 'MANAGEMENT'
    interface: 'ens4f0'
  - name: 'PUBLICAPI'
    interface: 'ens4f0'
  - name: 'STORAGE'
    interface: 'ens4f0'
  - name: 'TENANT'
    interface: 'ens44f0'
  - name: 'HEARTBEAT'
    interface: 'ens4f0'
internal_vip: '10.20.7.11'
public_vip: '10.20.7.11'
