# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160815_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='slave',
        ),
        migrations.AddField(
            model_name='resource',
            name='slavename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
