# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_resourceutilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='active',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='bookable',
        ),
    ]
