# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins', '0002_auto_20160815_1226'),
        ('dashboard', '0003_auto_20160815_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='slave',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='jenkins.JenkinsSlave'),
            preserve_default=False,
        ),
    ]
