# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20160813_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
