# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_resource_slave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='slavename',
        ),
    ]
