# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_resource_slavename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceUtilization',
        ),
    ]
